name: Multi-cloud CLI validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cloud-validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Azure CLI
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az version

      # Google Cloud SDK
      - name: Install Google Cloud SDK
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          sudo apt-get update -y && sudo apt-get install -y google-cloud-cli
          gcloud --version

      # AWS CLI v2
      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo apt-get install -y unzip
          unzip -q awscliv2.zip
          sudo ./aws/install
          aws --version

      # Simple diagnostic (no credentials)
      - name: Diagnostics (no-auth)
        run: |
          echo "Azure: listing built-in help..."
          az --help 1>/dev/null
          echo "GCP: printing components..."
          gcloud components list --quiet | head -n 10 || true
          echo "AWS: printing help..."
          aws help 1>/dev/null
          echo "Success: All three CLIs available on runner."
